import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ThemeProvider } from "@/providers/ThemeProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/AuthProvider";
const openSans = localFont({
  src: "./fonts/OpenSans.ttf", // Path to the font file
  variable: "--font-open-sans", // CSS variable name
  display: "swap", // Font loading behavior
  weight: "100 400 700 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className}  antialiased`}>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Toaster richColors position="bottom-left" />
          <ReduxProvider>
            <SessionProviderWrapper>
              <AuthProvider>{children}</AuthProvider>
            </SessionProviderWrapper>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
